CREATE TABLE `Currencies` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Code` varchar(100) NOT NULL,
  `Symbol` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO TimeSheet.Currencies (Name, Code, Symbol) VALUES ('Leke', 'ALL', 'Lek'),
 ('Dollars', 'USD', '$'),
 ('Afghanis', 'AFN', '؋'),
 ('Pesos', 'ARS', '$'),
 ('Guilders', 'AWG', 'ƒ'),
 ('Dollars', 'AUD', '$'),
 ('New Manats', 'AZN', 'ман'),
 ('Dollars', 'BSD', '$'),
 ('Dollars', 'BBD', '$'),
 ('Rubles', 'BYR', 'p.'),
 ('Euro', 'EUR', '€'),
 ('Dollars', 'BZD', 'BZ$'),
 ('Dollars', 'BMD', '$'),
 ('Bolivianos', 'BOB', '$b'),
 ('Convertible Marka', 'BAM', 'KM'),
 ('Pula', 'BWP', 'P'),
 ('Leva', 'BGN', 'лв'),
 ('Reais', 'BRL', 'R$'),
 ('Pounds', 'GBP', '£'),
 ('Dollars', 'BND', '$'),
 ('Riels', 'KHR', '៛'),
 ('Dollars', 'CAD', '$'),
 ('Dollars', 'KYD', '$'),
 ('Pesos', 'CLP', '$'),
 ('Yuan Renminbi', 'CNY', '¥'),
 ('Pesos', 'COP', '$'),
 ('Colón', 'CRC', '₡'),
 ('Kuna', 'HRK', 'kn'),
 ('Pesos', 'CUP', '₱'),
 ('Koruny', 'CZK', 'Kč'),
 ('Kroner', 'DKK', 'kr'),
 ('Pesos', 'DOP ', 'RD$'),
 ('Dollars', 'XCD', '$'),
 ('Pounds', 'EGP', '£'),
 ('Colones', 'SVC', '$'),
 ('Pounds', 'FKP', '£'),
 ('Dollars', 'FJD', '$'),
 ('Cedis', 'GHC', '¢'),
 ('Pounds', 'GIP', '£'),
 ('Quetzales', 'GTQ', 'Q'),
 ('Pounds', 'GGP', '£'),
 ('Dollars', 'GYD', '$'),
 ('Lempiras', 'HNL', 'L'),
 ('Dollars', 'HKD', '$'),
 ('Forint', 'HUF', 'Ft'),
 ('Kronur', 'ISK', 'kr'),
 ('Rupees', 'INR', 'Rp'),
 ('Rupiahs', 'IDR', 'Rp'),
 ('Rials', 'IRR', '﷼'),
 ('Pounds', 'IMP', '£'),
 ('New Shekels', 'ILS', '₪'),
 ('Dollars', 'JMD', 'J$'),
 ('Yen', 'JPY', '¥'),
 ('Pounds', 'JEP', '£'),
 ('Tenge', 'KZT', 'лв'),
 ('Won', 'KPW', '₩'),
 ('Won', 'KRW', '₩'),
 ('Soms', 'KGS', 'лв'),
 ('Kips', 'LAK', '₭'),
 ('Lati', 'LVL', 'Ls'),
 ('Pounds', 'LBP', '£'),
 ('Dollars', 'LRD', '$'),
 ('Switzerland Francs', 'CHF', 'CHF'),
 ('Litai', 'LTL', 'Lt'),
 ('Denars', 'MKD', 'ден'),
 ('Ringgits', 'MYR', 'RM'),
 ('Rupees', 'MUR', '₨'),
 ('Pesos', 'MXN', '$'),
 ('Tugriks', 'MNT', '₮'),
 ('Meticais', 'MZN', 'MT'),
 ('Dollars', 'NAD', '$'),
 ('Rupees', 'NPR', '₨'),
 ('Guilders', 'ANG', 'ƒ'),
 ('Dollars', 'NZD', '$'),
 ('Cordobas', 'NIO', 'C$'),
 ('Nairas', 'NGN', '₦'),
 ('Krone', 'NOK', 'kr'),
 ('Rials', 'OMR', '﷼'),
 ('Rupees', 'PKR', '₨'),
 ('Balboa', 'PAB', 'B/.'),
 ('Guarani', 'PYG', 'Gs'),
 ('Nuevos Soles', 'PEN', 'S/.'),
 ('Pesos', 'PHP', 'Php'),
 ('Zlotych', 'PLN', 'zł'),
 ('Rials', 'QAR', '﷼'),
 ('New Lei', 'RON', 'lei'),
 ('Rubles', 'RUB', 'руб'),
 ('Pounds', 'SHP', '£'),
 ('Riyals', 'SAR', '﷼'),
 ('Dinars', 'RSD', 'Дин.'),
 ('Rupees', 'SCR', '₨'),
 ('Dollars', 'SGD', '$'),
 ('Dollars', 'SBD', '$'),
 ('Shillings', 'SOS', 'S'),
 ('Rand', 'ZAR', 'R'),
 ('Rupees', 'LKR', '₨'),
 ('Kronor', 'SEK', 'kr'),
 ('Dollars', 'SRD', '$'),
 ('Pounds', 'SYP', '£'),
 ('New Dollars', 'TWD', 'NT$'),
 ('Baht', 'THB', '฿'),
 ('Dollars', 'TTD', 'TT$'),
 ('Lira', 'TRY', '₺'),
 ('Liras', 'TRL', '£'),
 ('Dollars', 'TVD', '$'),
 ('Hryvnia', 'UAH', '₴'),
 ('Pesos', 'UYU', '$U'),
 ('Sums', 'UZS', 'лв'),
 ('Bolivares Fuertes', 'VEF', 'Bs'),
 ('Dong', 'VND', '₫'),
 ('Rials', 'YER', '﷼'),
 ('Zimbabwe Dollars', 'ZWD', 'Z$'),
 ('Rupees', 'INR', '₹');

CREATE TABLE `Rates` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Rate` float NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Rate_FK` FOREIGN KEY (`ID`) REFERENCES `Currencies` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Taxes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Percentage` float NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Addresses` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Street` varchar(100) NOT NULL,
  `HouseNumber` smallint(6) DEFAULT NULL,
  `City` varchar(100) NOT NULL,
  `Country` varchar(100) NOT NULL,
  `ZipCode` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Kvk` varchar(100) NOT NULL,
  `Password` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `User_FK` FOREIGN KEY (`ID`) REFERENCES `Addresses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Companies` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `RegistrationNumber` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Companies_FK` FOREIGN KEY (`ID`) REFERENCES `Addresses` (`id`),
  CONSTRAINT `Companies_FK_1` FOREIGN KEY (`ID`) REFERENCES `Taxes` (`ID`),
  CONSTRAINT `Companies_FK_2` FOREIGN KEY (`ID`) REFERENCES `Rates` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Entries` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Start` datetime NOT NULL,
  `End` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Entries_FK` FOREIGN KEY (`ID`) REFERENCES `Companies` (`ID`),
  CONSTRAINT `Entries_FK_1` FOREIGN KEY (`ID`) REFERENCES `Users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

